### ISSUE TITLE
could you share me the datasets thanks 0.0

### ISSUE THREAD

**Issue by Spr1nt0a0** [farhanhubble/udacity-connect#1]

**Comment by farhanhubble** [comment]
Hi,
You can download the original MNIST training dataset (train.csv from https://www.kaggle.com/c/digit-recognizer/data) and then clone this repo and run the code in `segmented-generator.ipynb`. This will generate the data for segmentation. Alternatively if you do not have issues downloading about 2.2GB of data, you can grab all data from Kaggle at https://www.kaggle.com/farhanhubble/multimnistm2nist.

**Comment by Spr1nt0a0** [comment]
thank you very much
