### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/frozen_graph.pb'

### ISSUE THREAD

**Issue by pgirikishore** [farhanhubble/udacity-connect#3]
How to generate the drozen_graph.pb file?

**Comment by farhanhubble** [comment]
@pgirikishore you need to run the shell script [freeze.sh](https://github.com/farhanhubble/udacity-connect/blob/master/freeze.sh) after you have trained the MNIST model in `mnist.ipynb`. The shell script uses freeze.py (which comes from Google's TensorFlow repo) to freeze the model's weights and architecture.

**Comment by pgirikishore** [comment]
Thank you so much @farhanhubble 
Also, I'm wondering if it's possible to train a model for EMNIST (Extended MNIST) with 62 classes?
Any suggestions?

**Comment by farhanhubble** [comment]
@pgirikishore It should definitely be possible. You might have to tweak the code a little bit to accommodate the different number of classes.
